Acount/urls.py
from django.urls import path
from . import views
app_name="Acount"
urlpatterns=[
    path("login",views.user_login,name="login"),
    path("logout",views.user_logout,name="logout"),
    path("register",views.register,name="register"),
    path("change_pass",views.change_pass,name="change"),



]

Home/urls.py
from django.urls import path

from . import views
app_name="Home"
urlpatterns=[
    path("",views.Home,name="Home")
]

Rightness/urls.py
from django.contrib import admin
from django.urls import path,include
#from . import settings
#from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("Home.urls")),
    path("",include("Acount.urls")),
    path("",include("contact_us.urls")),
    path("",include("blog.urls")),
    path("",include("about_us.urls")),
    path("",include("admin_blog.urls"))
]

about_us/urls.py
from django.urls import path
from . import views

app_name="about_us"
urlpatterns=[
    path("about_us",views.about,name="about")
]

admin_blog/urls.py
from django.urls import path
from . import views

app_name="admin_blog"
urlpatterns=[
    path("admin_blog",views.admin_user,name="admin_blog"),
    path("blog_post",views.blog_coponents,name="blog_post"),
    path("add_post",views.add_post,name="add_post"),
    path("blog_profile",views.profile_blog,name="blog_profile")
]

blog/urls.py
from django.urls import path
from . import  views

app_name="blog"
urlpatterns=[
    path("blog",views.weblog,name="blog"),
    path("post_detail/<int:slug>",views.post_detail,name="post")
]

templates/admin_base.html
{% load static  %}
<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Shards Dashboard Lite - Free Bootstrap Admin Template – DesignRevision</title>
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="{% static "styles/shards-dashboards.1.1.0.min.css" %}">
    <link rel="stylesheet" href="{% static "styles/extras.1.1.0.min.css" %}">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </head>
  <body class="h-100">
    <div class="color-switcher animated">
      <h5>Accent Color</h5>
      <ul class="accent-colors">
        <li class="accent-primary active" data-color="primary">
          <i class="material-icons">check</i>
        </li>
        <li class="accent-secondary" data-color="secondary">
          <i class="material-icons">check</i>
        </li>
        <li class="accent-success" data-color="success">
          <i class="material-icons">check</i>
        </li>
        <li class="accent-info" data-color="info">
          <i class="material-icons">check</i>
        </li>
        <li class="accent-warning" data-color="warning">
          <i class="material-icons">check</i>
        </li>
        <li class="accent-danger" data-color="danger">
          <i class="material-icons">check</i>
        </li>
      </ul>
      <div class="actions mb-4">
        <a class="mb-2 btn btn-sm btn-primary w-100 d-table mx-auto extra-action" href="https://designrevision.com/downloads/shards-dashboard-lite/">
          <i class="material-icons">cloud</i> Download</a>
        <a class="mb-2 btn btn-sm btn-white w-100 d-table mx-auto extra-action" href="https://designrevision.com/docs/shards-dashboard-lite">
          <i class="material-icons">book</i> Documentation</a>
      </div>
      <div class="social-wrapper">
        <div class="social-actions">
          <h5 class="my-2">Help us Grow</h5>
          <div class="inner-wrapper">
            <a class="github-button" href="https://github.com/DesignRevision/shards-dashboard" data-icon="octicon-star" data-show-count="true" aria-label="Star DesignRevision/shards-dashboard on GitHub">Star</a>
            <!-- <iframe style="width: 91px; height: 21px;"src="https://yvoschaap.com/producthunt/counter.html#href=https%3A%2F%2Fwww.producthunt.com%2Fr%2Fp%2F112998&layout=wide" width="56" height="65" scrolling="no" frameborder="0" allowtransparency="true"></iframe> -->
          </div>
        </div>
        <div id="social-share" data-url="https://designrevision.com/downloads/shards-dashboard-lite/" data-text="🔥 Check out Shards Dashboard Lite, a free and beautiful Bootstrap 4 admin dashboard template!" data-title="share"></div>
        <div class="loading-overlay">
          <div class="spinner"></div>
        </div>
      </div>
      <div class="close">
        <i class="material-icons">close</i>
      </div>
    </div>
    <div class="color-switcher-toggle animated pulse infinite">
      <i class="material-icons">settings</i>
    </div>
    <div class="container-fluid">
      <div class="row">
        <!-- Main Sidebar -->
        <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
          <div class="main-navbar">
            <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
              <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
                <div class="d-table m-auto">
                  <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="{% static "images/shards-dashboards-logo.svg" %}" alt="Shards Dashboard">
                  <span class="d-none d-md-inline ml-1">Shards Dashboard</span>
                </div>
              </a>
              <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
              </a>
            </nav>
          </div>
          <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
            <div class="input-group input-group-seamless ml-3">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fas fa-search"></i>
                </div>
              </div>
              <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
          </form>
          <div class="nav-wrapper">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url "admin_blog:admin_blog" %}">
                  <i class="material-icons">edit</i>
                  <span>Blog Dashboard</span>
                </a>
              </li>

               {% if request.user.profile.blog_admin == True %}
              <li class="nav-item">
                <a class="nav-link " href="{% url "admin_blog:blog_post" %}">
                  <i class="material-icons">vertical_split</i>
                  <span>Blog Posts</span>
                </a>
              </li>


              <li class="nav-item">
                <a class="nav-link " href="{% url "admin_blog:add_post" %}">
                  <i class="material-icons">note_add</i>
                  <span>Add New Post</span>
                </a>
              </li>
                {% endif %}
              <li class="nav-item">
                <a class="nav-link " href="{% url "admin_blog:blog_profile" %}">
                  <i class="material-icons">person</i>
                  <span>User Profile</span>
                </a>
              </li>

            </ul>
          </div>
        </aside>
        <!-- End Main Sidebar -->



        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
          <div class="main-navbar sticky-top bg-white">
            <!-- Main Navbar -->
            <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
              <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
                <div class="input-group input-group-seamless ml-3">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="fas fa-search"></i>
                    </div>
                  </div>
                  <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
              </form>
              <ul class="navbar-nav border-left flex-row ">
                <li class="nav-item border-right dropdown notifications">
                  <a class="nav-link nav-link-icon text-center" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="nav-link-icon__wrapper">
                      <i class="material-icons">&#xE7F4;</i>
                      <span class="badge badge-pill badge-danger">2</span>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-small" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">
                      <div class="notification__icon-wrapper">
                        <div class="notification__icon">
                          <i class="material-icons">&#xE6E1;</i>
                        </div>
                      </div>
                      <div class="notification__content">
                        <span class="notification__category">Analytics</span>
                        <p>Your website’s active users count increased by
                          <span class="text-success text-semibold">28%</span> in the last week. Great job!</p>
                      </div>
                    </a>
                    <a class="dropdown-item" href="#">
                      <div class="notification__icon-wrapper">
                        <div class="notification__icon">
                          <i class="material-icons">&#xE8D1;</i>
                        </div>
                      </div>
                      <div class="notification__content">
                        <span class="notification__category">Sales</span>
                        <p>Last week your store’s sales count decreased by
                          <span class="text-danger text-semibold">5.52%</span>. It could have been worse!</p>
                      </div>
                    </a>
                    <a class="dropdown-item notification__all text-center" href="#"> View all Notifications </a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle mr-2" src="{{ request.user.profile.image.url }}" alt="User Avatar">
                    <span class="d-none d-md-inline-block">{{ request.user.get_full_name }}</span>
                  </a>
                  <div class="dropdown-menu dropdown-menu-small">



                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{% url "Acount:logout" %}">
                      <i class="material-icons text-danger">&#xE879;</i> Logout </a>
                  </div>
                </li>
              </ul>
              <nav class="nav">
                <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                  <i class="material-icons">&#xE5D2;</i>
                </a>
              </nav>
            </nav>
          </div>

            {% block content %}



            {% endblock %}























<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Blog</a>
              </li>
            </ul>
            <span class="copyright ml-auto my-auto mr-2">Copyright © 2018
              <a href="https://designrevision.com" rel="nofollow">DesignRevision</a>
            </span>
          </footer>
        </main>
      </div>
    </div>
    <div class="promo-popup animated">
      <a href="http://bit.ly/shards-dashboard-pro" class="pp-cta extra-action">
        <img src="https://dgc2qnsehk7ta.cloudfront.net/uploads/sd-blog-promo-2.jpg"> </a>
      <div class="pp-intro-bar"> Need More Templates?
        <span class="close">
          <i class="material-icons">close</i>
        </span>
        <span class="up">
          <i class="material-icons">keyboard_arrow_up</i>
        </span>
      </div>
      <div class="pp-inner-content">
        <h2>Shards Dashboard Pro</h2>
        <p>A premium & modern Bootstrap 4 admin dashboard template pack.</p>
        <a class="pp-cta extra-action" href="http://bit.ly/shards-dashboard-pro">Download</a>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
    <script src="{% static "scripts/extras.1.1.0.min.js" %}"></script>
    <script src="{% static "scripts/shards-dashboards.1.1.0.min.js" %}"></script>
    <script src="{% static "scripts/app/app-blog-overview.1.1.0.js" %}"></script>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--favicon icon-->
    <link rel="icon" href="{% static "img/favicon.png" %}" type="image/png" sizes="16x16">

    <!--title-->
    {% block titel %}

    {% endblock %}
    <!--build:css-->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- endbuild -->
</head>

<body>

<!--preloader start-->
<div id="preloader">
    <div class="loader1">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--preloader end-->
<!--header section start-->
<header class="header position-relative z-9">
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-dark navbar-theme-primary fixed-top headroom">
        <div class="container position-relative">
            <a class="navbar-brand mr-lg-3" href="index.html">
                <img class="navbar-brand-dark" src="{% static "img/logo-white.png" %}" alt="منوی تصویر">
                <img class="navbar-brand-light" src="{% static "img/logo-color.png" %}" alt="منوی تصویر">
            </a>
            <div class="navbar-collapse collapse" id="navbar-default-primary">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="#">
                                <img src="{% static "img/logo-color.png" %}" alt="منوی تصویر">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <i class="fas fa-times" data-toggle="collapse" role="button"
                               data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                               aria-expanded="false" aria-label="تغییر پیمایش"></i>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover ml-auto">
                {% if request.user.profile %}
                <li class="nav-item">
                        <a class="nav-link" href="{% url "admin_blog:blog_post" %}">ورود به پنل کاربری</a>

                    </li>
                {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "Home:Home" %}">خانه</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "about_us:about" %}">درباره ما</a>
                    </li>

                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "blog:blog" %}">وبلاگ</a>
                    </li>


                    <li class="nav-item"><a class="nav-link" href="{% url "contact_us:contact" %}">تماس با ما</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url "Acount:logout" %}">خروج از حساب کاربری</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url "Home:Home" %}">{{ request.user.username }}</a></li>
                        <li class="nav-item" ><img width="50px" height="50px" style="border-radius: 80px" src="{{ request.user.profile.image.url }}"></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url "Acount:login" %}">ورود</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url "Acount:register" %}">ثبت نام</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="d-flex align-items-center">
                <button class="navbar-toggler ml-2" type="button" data-toggle="collapse"
                        data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                        aria-expanded="false" aria-label="تغییر پیمایش">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
</header>

{% block content %}

{% endblock %}

<!--footer section start-->
<footer class="footer-wrap">
    <div class="footer footer-top section section-md bg-primary text-white">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-4 mb-4">
                    <a class="footer-brand mr-lg-5 d-flex" href="index.html">
                        <img src="{% static "img/logo-white.png" %}" class="mr-3" alt="آرم پاورقی">
                    </a>
                    <p class="my-4">قبل از درگاه های صداگذاری فنی ، بهترین روش های تعاملی را به صورت تعاملی آزاد
                        کنید.</p>
                    <div class="btn-wrapper mt-4">
                        <button class="btn btn-icon-only btn-pill btn-twitter mr-2 icon icon-xs icon-shape"
                                type="button" data-toggle="tooltip" data-placement="top" title=""
                                data-original-title="4000 دنبال کننده">
                            <span aria-hidden="true" class="fab fa-twitter"></span>
                        </button>
                        <button class="btn btn-icon-only btn-pill btn-facebook mr-2 icon icon-xs icon-shape"
                                type="button" data-toggle="tooltip" data-placement="top" title=""
                                data-original-title="5000 لایک">
                            <span aria-hidden="true" class="fab fa-facebook-f"></span>
                        </button>
                        <button class="btn btn-icon-only btn-pill btn-youtube mr-2 icon icon-xs icon-shape"
                                type="button" data-toggle="tooltip" data-placement="top" title=""
                                data-original-title="4000 عضویت">
                            <span aria-hidden="true" class="fab fa-youtube"></span>
                        </button>
                        <button class="btn btn-icon-only btn-pill btn-dribbble icon icon-xs icon-shape" type="button"
                                data-toggle="tooltip" data-placement="top" title="" data-original-title="2000 پروژه">
                            <span aria-hidden="true" class="fab fa-dribbble"></span>
                        </button>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3 mb-4 mb-lg-0">
                    <h5 class="mb-4">شرکت</h5>
                    <ul class="links-vertical">
                        <li><a target="_blank" href="#">درباره ما</a></li>
                        <li><a target="_blank" href="#">مشاغل</a></li>
                        <li><a target="_blank" href="#">مشتریان</a></li>
                        <li><a target="_blank" href="#">انجمن</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 mb-4 mb-lg-0">
                    <h5 class="mb-4">منابع</h5>
                    <ul class="links-vertical">
                        <li><a target="_blank" href="#">راهنمایی</a></li>
                        <li><a target="_blank" href="#">مناسبت ها</a></li>
                        <li><a target="_blank" href="#">جلسات زنده</a></li>
                        <li><a target="_blank" href="#">منابع باز</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <h5 class="mb-4">حمایت کردن</h5>
                    <ul class="links-vertical">
                        <li><a target="_blank" href="#">راهنمایی</a></li>
                        <li><a target="_blank" href="#">پشتیبانی فنی</a></li>
                        <li><a target="_blank" href="#">وضعیت شبکه</a></li>
                        <li><a target="_blank" href="#">با پشتیبانی تماس بگیرید</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer py-3 bg-primary text-white border-top border-variant-default">
        <div class="container">
            <div class="row">
                <div class="col p-3">
                    <div class="d-flex text-center justify-content-center align-items-center">
                        <p class="copyright pb-0 mb-0">حق چاپ © 2021. کلیه حقوق محفوظ است توسط
                            <a href="https://themeforest.net/user/themetags" target="_blank">Themefix</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--footer section end-->
<!--scroll bottom to top button start-->
<button class="scroll-top scroll-to-target" data-target="html">
    <span class="fas fa-hand-point-up"></span>
</button>
<!--scroll bottom to top button end-->
<!--build:js-->
<script src="{% static "js/vendors/jquery-3.5.1.min.js" %}"></script>
<!--script src="{% static "js/vendors/popper.min.js" %}"></script>-->
<script src="{% static "js/vendors/bootstrap.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.easing.min.js" %}"></script>
<script src="{% static "js/vendors/mixitup.min.js" %}"></script>
<script src="{% static "js/vendors/headroom.min.js" %}"></script>
<script src="{% static "js/vendors/smooth-scroll.min.js" %}"></script>
<script src="{% static "js/vendors/wow.min.js" %}"></script>
<script src="{% static "js/vendors/owl.carousel.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.waypoints.min.js" %}"></script>
<!--<script src="assets/js/vendors/countUp.min.js"></script>-->
<script src="{% static "js/vendors/jquery.countdown.min.js" %}"></script>
<script src="{% static "js/vendors/validator.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
<!--endbuild-->

</body>
</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--favicon icon-->
    <link rel="icon" href="{% static "img/favicon.png" %}" type="image/png" sizes="16x16">

    <!--title-->
    {% block titel %}

    {% endblock %}
    <!--build:css-->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- endbuild -->
</head>

<body>

<!--preloader start-->
<div id="preloader">
    <div class="loader1">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--preloader end-->
<!--header section start-->
<header class="header position-relative z-9">
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-dark navbar-theme-primary fixed-top headroom">
        <div class="container position-relative">
            <a class="navbar-brand mr-lg-3" href="index.html">
                <img class="navbar-brand-dark" src="{% static "img/logo-white.png" %}" alt="منوی تصویر">
                <img class="navbar-brand-light" src="{% static "img/logo-color.png" %}" alt="منوی تصویر">
            </a>
            <div class="navbar-collapse collapse" id="navbar-default-primary">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="#">
                                <img src="{% static "img/logo-color.png" %}" alt="منوی تصویر">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <i class="fas fa-times" data-toggle="collapse" role="button"
                               data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                               aria-expanded="false" aria-label="تغییر پیمایش"></i>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "Home:Home" %}">خانه</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "about_us:about" %}">درباره ما</a>
                    </li>

                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "blog:blog" %}">وبلاگ</a>
                    </li>


                    <li class="nav-item"><a class="nav-link" href="{% url "contact_us:contact" %}">تماس با ما</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url "Home:Home" %}">خروج از حساب کاربری</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url "Home:Home" %}">{{ request.user.username }}</a></li>
                        <li class="nav-item" ><img width="50px" height="50px" style="border-radius: 80px" src="{{ request.user.profile.image.url }}"></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url "Acount:login" %}">ورود</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url "Acount:register" %}">ثبت نام</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="d-flex align-items-center">
                <button class="navbar-toggler ml-2" type="button" data-toggle="collapse"
                        data-target="#navbar-default-primary" aria-controls="navbar-default-primary"
                        aria-expanded="false" aria-label="تغییر پیمایش">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>
</header>

{% block content %}

{% endblock %}


<script src="{% static "js/vendors/jquery-3.5.1.min.js" %}"></script>
<!--script src="{% static "js/vendors/popper.min.js" %}"></script>-->
<script src="{% static "js/vendors/bootstrap.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.easing.min.js" %}"></script>
<script src="{% static "js/vendors/mixitup.min.js" %}"></script>
<script src="{% static "js/vendors/headroom.min.js" %}"></script>
<script src="{% static "js/vendors/smooth-scroll.min.js" %}"></script>
<script src="{% static "js/vendors/wow.min.js" %}"></script>
<script src="{% static "js/vendors/owl.carousel.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.waypoints.min.js" %}"></script>
<!--<script src="assets/js/vendors/countUp.min.js"></script>-->
<script src="{% static "js/vendors/jquery.countdown.min.js" %}"></script>
<script src="{% static "js/vendors/validator.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>