Acount/urls.py
from django.urls import path
from . import views
app_name="Acount"
urlpatterns=[
    path("login",views.user_login,name="login"),
    path("logout",views.user_logout,name="logout"),
    path("register",views.register,name="register"),
    path("change_pass",views.change_pass,name="change"),



]

Home/urls.py
from django.urls import path

from . import views
app_name="Home"
urlpatterns=[
    path("",views.Home,name="Home")
]

Rightness/urls.py
from django.contrib import admin
from django.urls import path,include
#from . import settings
#from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("Home.urls")),
    path("",include("Acount.urls")),
    path("",include("contact_us.urls")),
    path("",include("blog.urls")),
    path("",include("about_us.urls")),
    path("",include("admin_blog.urls"))
]

Acount/models.py
from django.db import models
from django.contrib.auth.models import User

class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=50)
    email=models.EmailField()
    password=models.CharField(max_length=20)
    addres=models.TextField()
    discription=models.TextField()
    power=models.CharField(max_length=50,blank=True,null=True)
    image=models.ImageField(default="defult/index.png",upload_to="profile_user",null=True,blank=True)
    blog_admin=models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

Acount/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .models import profile
from django.conf import settings
from django.core.mail import send_mail
import random
import numpy
def user_login(request):

    if request.user.is_authenticated==True:
        return redirect("Home:Home")
    else:
        if request.method=="POST":
            username=request.POST.get("username")
            password=request.POST.get("password")

            user=authenticate(username=username,password=password)

            if user is not None:
                login(request,user)

                return redirect("Home:Home")




    return render(request,"Acount/login.html")

def user_logout(request):
    logout(request)
    return redirect("Home:Home")

def register(request):


    context={
        "errors":[]
    }

    if request.user.is_authenticated==True:
        return redirect("Home:Home")



    if request.method=="POST":
        username=request.POST.get("username")
        email=request.POST.get("email")
        password=request.POST.get("password")
        password2=request.POST.get("password2")

        if User.objects.filter(username=username).exists():
            context["errors"].append("نام کاربری از قبل وجود دارد")
            return render(request,"Acount/register.html",context)

        elif password != password2:
            context["errors"].append("رمز ها شباهت ندارد")

        elif User.objects.filter(email=email).exists():
            context["errors"].append("ایمیل از قبل وجود دارد")
            return render(request,"Acount/register.html",context)

        else:
            user=User.objects.create(username=username,password=password,email=email)
            user.set_password(password)
            user.save()

            subject = "به وبسایت من خوش آمدید"
            message = f" سلام  {username} " \
                      f"به وبسایت من خوش اومدی" \
                      f"برای دریافت برنامه ورزشی وارد حساب کاربری خودت شو و فرم رو تکمیل کن" \
                      f"من برنامه روزنامه رو برات ارسال میکنم"
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [user.email, ]
            send_mail(subject, message, email_from, recipient_list)

            subject2="ثبت نام جدید در سایت"
            message2=f"یک شخص جدید در سایت شما ثبت نام کرد" \
                      f": نام کاربری{username}" \
                      f":ایمیل{email}"
            email_from2 = settings.EMAIL_HOST_USER
            recipient_list2 = ["mahdiramazani1281@gmail.com", ]
            send_mail(subject2, message2, email_from2, recipient_list2)
            login(request,user)
            return redirect("Home:Home")


    return render(request,"Acount/register.html",context)


def change_pass(request):

    context={
        "errors":[],
    }


    if request.method=="POST":
        email=request.POST.get("email")
        pass1=request.POST.get("password1")
        pass2=request.POST.get("password2")

        if pass1 != pass2:
            context["errors"].append("رمز ها شباهن ندارد")
            return render(request, "Acount/change-password.html", context)

        if User.objects.filter(email=email).exists():

            user=User.objects.get(email=email)

            user.set_password(pass1)
            user.save()


            login(request,user)
            return redirect("Home:Home")

        else:
            context["errors"].append("ایمیل وجود ندارد")
            return render(request,"Acount/change-password.html",context)



    return render(request,"Acount/change-password.html")

Acount/templates/Acount/change-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--favicon icon-->
    <link rel="icon" href="{% static "img/favicon.png" %}" type="image/png" sizes="16x16">

    <!--title-->
    <title>قالب</title>

    <!--build:css-->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- endbuild -->
</head>

<body>

<!--preloader start-->
<div id="preloader">
    <div class="loader1">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--preloader end-->
<div class="main">

    <!--sign up section start-->
    <section class="section section-lg py-0 min-vh-100 bg-soft">
        <div class="container-fluid p-0">
            <div class="row align-items-center min-vh-100 justify-content-center no-gutters">
                <div class="col-12 col-md-7 col-lg-8 col-xl-8 d-none d-md-none d-xl-block"
                     style="background-image: url('{% static 'img/slider-img-4.jpg' %}');">
                    <!-- Image -->
                    <div class="d-flex align-items-center min-vh-100 bg-gradient-primary text-white">
                        <div class="position-relative w-75 p-8">
                            <h1 class="display-2">رمزعبور خود را تغییر دهید</h1>
                            <p class="lead">صورت خود را همیشه به سمت آفتاب نگه دارید - و سایه ها پشت سر شما قرار می
                                گیرند. به طور مداوم طاقچه های کاملاً تحقیق شده را دنبال کنید در حالی که سیستم عامل های
                                به موقع.</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-5 col-lg-4 col-xl-4">
                    <div class="login-signup-wrap bg-soft p-5 p-md-4 px-lg-6">
                        <!-- Heading -->
                        <h3 class="text-center">رمز عبور را تغییر دهید</h3>

                        <!-- Subheading -->
                        <p class="text-muted text-center mb-5">
                            رمز ورود جدید خود را وارد کنید
                        </p>

                        {% if errors %}
                            <p class="text-muted text-center mb-5 badge-warning">
                                {{ errors.0 }}

                            </p>
                        {% endif %}
                        <!-- Form -->

                            <form class="login-signup-form" action="#" method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="font-weight-bold">ایمیل خود را وارد کنید</label>
                                <div class="input-group input-group-merge">
                                    <div class="input-icon">
                                        <i class="ti-lock"></i>
                                    </div>
                                    <input type="email" class="form-control" name="email"
                                           placeholder="ایمیل خود را وارد کنید">
                                </div>

                                <label class="font-weight-bold">رمز جدید خود را وارد کنید</label>
                                <div class="input-group input-group-merge">
                                    <div class="input-icon">
                                        <i class="ti-lock"></i>
                                    </div>
                                    <input type="password" class="form-control" name="password1"
                                           placeholder="رمز خود را وارد کنید">
                                </div>


                                <label class="font-weight-bold">رمز خود را تایید کنید</label>
                                <div class="input-group input-group-merge">
                                    <div class="input-icon">
                                        <i class="ti-lock"></i>
                                    </div>
                                    <input type="password" class="form-control" name="password2"
                                           placeholder="رمز خود را وارد کنید">
                                </div>
                            </div>
                            <button class="btn btn-block btn-secondary mt-4 mb-3" type="submit">تغییر رمز عبور</button>


                        <!-- Submit -->



                        <!-- Submit -->

                        <div class="text-center">
                            <p class="font-small">رمز عبور خود را به خاطر می آورید؟ <a href="{% url "Acount:login" %}">ورود
                                به سیستم</a> .</p>
                        </div>

                        </form>
                    </div>
                </div>
            </div> <!-- / .row -->
        </div>
    </section>
    <!--sign up section end-->

</div>

<!--scroll bottom to top button start-->
<button class="scroll-top scroll-to-target" data-target="html">
    <span class="fas fa-hand-point-up"></span>
</button>
<!--scroll bottom to top button end-->
<!--build:js-->
<script src="{% static "js/vendors/jquery-3.5.1.min.js" %}"></script>
<script src="{% static "js/vendors/popper.min.js" %}"></script>
<script src="{% static "js/vendors/bootstrap.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.easing.min.js" %}"></script>
<script src="{% static "js/vendors/mixitup.min.js" %}"></script>
<script src="{% static "js/vendors/headroom.min.js" %}"></script>
<script src="{% static "js/vendors/smooth-scroll.min.js" %}"></script>
<script src="{% static "js/vendors/wow.min.js" %}"></script>
<script src="{% static "js/vendors/owl.carousel.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.waypoints.min.js" %}"></script>
<!--<script src="assets/js/vendors/countUp.min.js"></script>-->
<script src="{% static "js/vendors/jquery.countdown.min.js" %}"></script>
<script src="{% static "js/vendors/validator.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
<!--endbuild-->


</body>
</html>

Acount/templates/Acount/confuremail.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--favicon icon-->
    <link rel="icon" href="{% static "img/favicon.png" %}" type="image/png" sizes="16x16">

    <!--title-->
    <title>قالب</title>

    <!--build:css-->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- endbuild -->
</head>

<body>

<!--preloader start-->
<div id="preloader">
    <div class="loader1">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--preloader end-->
<div class="main">

    <!--sign up section start-->
    <section class="section section-lg py-0 min-vh-100 bg-soft">
        <div class="container-fluid p-0">
            <div class="row align-items-center min-vh-100 justify-content-center no-gutters">
                <div class="col-12 col-md-7 col-lg-8 col-xl-8 d-none d-md-none d-xl-block" style="background-image: url('{% static 'img/slider-img-4.jpg' %}');">
                    <!-- Image -->
                    <div class="d-flex align-items-center min-vh-100 bg-gradient-primary text-white">
                        <div class="position-relative w-75 p-8">
                            <h1 class="display-2">رمزعبور خود را تغییر دهید</h1>
                            <p class="lead">صورت خود را همیشه به سمت آفتاب نگه دارید - و سایه ها پشت سر شما قرار می گیرند. به طور مداوم طاقچه های کاملاً تحقیق شده را دنبال کنید در حالی که سیستم عامل های به موقع.</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-5 col-lg-4 col-xl-4">
                    <div class="login-signup-wrap bg-soft p-5 p-md-4 px-lg-6">
                        <!-- Heading -->
                        <h3 class="text-center">رمز عبور را تغییر دهید</h3>

                        <!-- Subheading -->
                        <p class="text-muted text-center mb-5">
                            رمز ورود جدید خود را وارد کنید
                        </p>

                        {% if errors %}
                        <p class="text-muted text-center mb-5 badge-warning">
                            {{errors.0 }}

                        </p>
                        {% endif %}
                        <!-- Form -->
                        <form class="login-signup-form" action="#" method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="font-weight-bold">کد تایید را وارد کنید</label>
                                <div class="input-group input-group-merge">
                                    <div class="input-icon">
                                        <i class="ti-lock"></i>
                                    </div>
                                    <input type="text" class="form-control" name="code"
                                           placeholder="کد تایید را وارد کنید">
                                </div>
                            </div>
                            <button class="btn btn-block btn-secondary mt-4 mb-3">رمز عبور را تغییر دهید</button>




                        </form>
                    </div>
                </div>
            </div> <!-- / .row -->
        </div>
    </section>
    <!--sign up section end-->

</div>

<!--scroll bottom to top button start-->
<button class="scroll-top scroll-to-target" data-target="html">
    <span class="fas fa-hand-point-up"></span>
</button>
<!--scroll bottom to top button end-->
<!--build:js-->
<script src="{% static "js/vendors/jquery-3.5.1.min.js" %}"></script>
<script src="{% static "js/vendors/popper.min.js" %}"></script>
<script src="{% static "js/vendors/bootstrap.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.easing.min.js" %}"></script>
<script src="{% static "js/vendors/mixitup.min.js" %}"></script>
<script src="{% static "js/vendors/headroom.min.js" %}"></script>
<script src="{% static "js/vendors/smooth-scroll.min.js" %}"></script>
<script src="{% static "js/vendors/wow.min.js" %}"></script>
<script src="{% static "js/vendors/owl.carousel.min.js" %}"></script>
<script src="{% static "js/vendors/jquery.waypoints.min.js" %}"></script>
<!--<script src="assets/js/vendors/countUp.min.js"></script>-->
<script src="{% static "js/vendors/jquery.countdown.min.js" %}"></script>
<script src="{% static "js/vendors/validator.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
<!--endbuild-->


</body>
</html>

Acount/templates/Acount/login.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
<!--header section end-->

<div class="main">

    <!--login section start-->
    <section class="section section-lg section-header position-relative min-vh-100 flex-column d-flex justify-content-center" style="background: url('{% static 'img/slider-bg-1.svg' %}')no-repeat center bottom / cover">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-7 col-lg-6">
                    <div class="hero-content-left text-white">
                        <h1 class="display-2">خوش آمدید !</h1>
                        <p class="lead">
                            صورت خود را همیشه به سمت آفتاب نگه دارید - و سایه ها پشت سر شما قرار می گیرند.
                        </p>
                    </div>
                </div>
                <div class="col-md-5 col-lg-5">
                    <div class="card login-signup-card shadow-lg mb-0">
                        <div class="card-body px-md-5 py-5">
                            <div class="mb-5">
                                <h3>وارد شدن</h3>
                                <p class="text-muted">برای ادامه وارد حساب خود شوید.</p>
                            </div>

                            <!--login form-->
                            <form class="login-signup-form"  method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="font-weight-bold">ام کاربری</label>
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-email"></i>
                                        </div>
                                        <input type="text" class="form-control"  name="username" placeholder="ایمیل خود را وارد کنید" required="">
                                    </div>
                                </div>
                                <!-- Password -->
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label class="font-weight-bold">کلمه عبور</label>
                                        </div>
                                        <div class="col-auto">
                                            <a href="{% url "Acount:change" %}" class="form-text small text-muted">
                                                رمز عبور خود را فراموش کرده اید؟
                                            </a>
                                        </div>
                                    </div>
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-lock"></i>
                                        </div>
                                        <input type="password" name="password" class="form-control" placeholder="رمز ورود خود را وارد کنید">
                                    </div>
                                </div>

                                <!-- Submit -->
                                <button class="btn btn-block btn-secondary mt-4 mb-3">ورود</button>

                            </form>
                        </div>
                        <div class="card-footer bg-soft text-center border-top px-md-5"><small>ثبت نشده؟ </small>
                            <a href="{% url "Acount:register" %}" class="small">ایجاد حساب کاربری</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

Acount/templates/Acount/register.html
{% extends "base2.html" %}
{% load static  %}
{% block content %}
<!--header section end-->

<div class="main">

    <!--sign up section start-->
    <section class="section section-lg section-header position-relative min-vh-100 flex-column d-flex justify-content-center" style="background: url('{% static 'img/slider-bg-1.svg' %}')no-repeat center bottom / cover">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-7 col-lg-6">
                    <div class="hero-content-left text-white">
                        <h1 class="display-2">حساب کاربری برای خود بسازید</h1>
                        <p class="lead">
                            صورت خود را همیشه به سمت آفتاب نگه دارید - و سایه ها پشت سر شما قرار می گیرند.
                        </p>
                    </div>
                </div>
                <div class="col-md-5 col-lg-5">
                    <div class="card login-signup-card shadow-lg mb-0">
                        <div class="card-body px-md-5 py-5">
                            <div class="mb-5">
                                <h3>ایجاد حساب</h3>
                                <p class="text-muted">برای ادامه وارد حساب خود شوید.</p>
                            </div>
                            <!--sign up form-->
                            <form class="login-signup-form" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <!-- Label -->
                                    {% if errors %}
                                    <div class="container">
                                        <p class="text text-center">
                                            {{ errors.0 }}
                                        </p>
                                    </div>
                                    {% endif %}
                                    <label class="font-weight-bold">
                                        اسم شما
                                    </label>
                                    <!-- Input group -->
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-user"></i>
                                        </div>
                                        <input type="text" name="username" class="form-control" placeholder="نام کاربری خودت رو وارد کن" required="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <!-- Label -->
                                    <label class="font-weight-bold">
                                        آدرس ایمیل
                                    </label>
                                    <!-- Input group -->
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-email"></i>
                                        </div>
                                        <input type="email"  name="email" class="form-control" placeholder="name@address.com" required="">
                                    </div>
                                </div>

                                <!-- Password -->
                                <div class="form-group">
                                    <!-- Label -->
                                    <label class="font-weight-bold">
                                        کلمه عبور
                                    </label>
                                    <!-- Input group -->
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-lock"></i>
                                        </div>
                                        <input type="password" name="password" class="form-control" placeholder="رمز ورود خود را وارد کنید">
                                    </div>
                                </div>
                            <div class="form-group">
                                    <!-- Label -->
                                    <label class="font-weight-bold">
                                        تکرار کلمه عبور
                                    </label>
                                    <!-- Input group -->
                                    <div class="input-group input-group-merge">
                                        <div class="input-icon">
                                            <i class="ti-lock"></i>
                                        </div>
                                        <input type="password" name="password2" class="form-control" placeholder="رمز عبور را مجددا وارد کنید">
                                    </div>
                                </div>

                                <div class="my-4">
                                    <div class="form-check square-check">
                                        <input class="form-check-input" type="checkbox" value="" id="check-terms">
                                        <label class="form-check-label" for="check-terms">
                                            من با <a href="#">شرایط و ضوابط</a> موافقم<a href="#"></a>
                                        </label>
                                    </div>
                                </div>

                                <!-- Submit -->
                                <button class="btn btn-block btn-secondary border-radius mt-4 mb-3">
                                    ثبت نام
                                </button>
                            </form>
                        </div>
                        <div class="card-footer bg-soft text-center border-top px-md-5"><small>قبلاً ثبت نام کرده اید؟ </small>
                            <a href="{% url "Acount:login" %}" class="small">وارد شدن</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--sign up section end-->


</div>


</body>

</html>
{% endblock %}